name: Create Pull Request on Commit

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Enter the source branch for the pull request'
        required: true
        default: 'develop'
      destination:
        description: 'Enter the destination branch for the pull request'
        required: true
        default: 'test'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:

       - name: create a Pull Request
         run: |
           curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/liorlavi1/demo-github-action-trigger/pulls \
            -d '{"title":"Testing pull request","body":"Please pull these awesome changes in!","head":${{ github.event.inputs.source }},"base":${{ github.event.inputs.destination }}}'
            
